config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'main#index'

  get 'vyrobnictvo-prodazh-montazh-pidvikonnykiv' => 'main#about', as: :about

  get 'informaciia' => 'main#publications', as: :information
  get 'informaciia/:title' => 'main#publication', as: :one_publication

  get 'testimonials' => 'testimonial#list', as: :testimonials

  get 'aktcii' => 'main#promotions', as: :promotions
  get 'aktcii/:title' => 'main#one_promotions', as: :one_promotions

  get 'kontakty' => 'main#contacts', as: :contacts

  get 'dostavka-i-oplata' => 'main#warranty', as: :warranty

  get 'pidvikonnja-vidlyvy' => 'main#windowsill', as: :windowsill
  get 'pidvikonnja-vidlyvy/:title' => 'main#one_windowsill', as: :one_windowsill
  get 'gag/:title' => 'main#gag', as: :one_gag

  get 'pokrivlja-ogorozhi' => 'roof_railing#index', as: :roof_rail
  get 'pokrivlja-ogorozhi/profnastyl-metaloprofil' => 'roof_railing#deck_list', as: :roof_rail_decking
  get 'pokrivlja-ogorozhi/profnastyl-metaloprofil/:title' => 'roof_railing#decking', as: :one_decking

  get 'pokrivlja-ogorozhi/metalocherepitcja' => 'roof_railing#metal_tile_list', as: :metal_tile
  get 'pokrivlja-ogorozhi/metalocherepitcja/:title' => 'roof_railing#metal_tile', as: :metal_tile_item

  get 'pokrivlja-ogorozhi/lystovyj-metal' => 'roof_railing#sheet_metal_list', as: :sheet_metal
  get 'pokrivlja-ogorozhi/lystovyj-metal/:title' => 'roof_railing#sheet_metal', as: :sheet_metal_item

  get 'pokrivlja-ogorozhi/pokrivelni-dobirni-elementy' => 'roof_railing#choicest_items', as: :choicest_items
  get 'pokrivlja-ogorozhi/pokrivelni-dobirni-elementy/the-roof' => 'roof_railing#choicest_roof_items', as: :choicest_roof_items
  get 'pokrivlja-ogorozhi/pokrivelni-dobirni-elementy/the-fence' => 'roof_railing#choicest_fence_items', as: :choicest_fence_items
  get 'pokrivlja-ogorozhi/pokrivelni-dobirni-elementy/:title' => 'roof_railing#choicest_item', as: :choicest_item

  get 'pokrivlja-ogorozhi/kriplennja-germetyka-dlja-pokrivli' => 'roof_railing#mounting_and_sealants', as: :mounting_and_sealants
  get 'pokrivlja-ogorozhi/kriplennja-germetyka-dlja-pokrivli/hermetyky' => 'roof_railing#sealants', as: :sealants
  get 'pokrivlja-ogorozhi/kriplennja-germetyka-dlja-pokrivli/hermetyky/:title' => 'roof_railing#sealant', as: :sealant
  get 'pokrivlja-ogorozhi/kriplennja-germetyka-dlja-pokrivli/kriplennya' => 'roof_railing#mounting', as: :fasteners
  get 'pokrivlja-ogorozhi/kriplennja-germetyka-dlja-pokrivli/kriplennya/:title' => 'roof_railing#fastener', as: :fastener

  get 'pokrivlja-ogorozhi/pokrivelni-plivky' => 'roof_railing#roofing_membrane', as: :roofing_membrane
  get 'pokrivlja-ogorozhi/pokrivelni-plivky/parobaryer' => 'roof_railing#vapour_barrier', as: :vapour_barrier
  get 'pokrivlja-ogorozhi/pokrivelni-plivky/parobaryer/:title' => 'roof_railing#vapour_barrier_item', as: :vapour_barrier_item

  get 'pokrivlja-ogorozhi/pokrivelni-plivky/hidrobaryer' => 'roof_railing#hydro_barrier', as: :hydro_barrier
  get 'pokrivlja-ogorozhi/pokrivelni-plivky/hidrobaryer/:title' => 'roof_railing#hydro_barrier_item', as: :hydro_barrier_item

  get 'pokrivlja-ogorozhi/pokrivelni-plivky/membrana' => 'roof_railing#membrane', as: :membrane
  get 'pokrivlja-ogorozhi/pokrivelni-plivky/membrana/:title' => 'roof_railing#membrane_item', as: :membrane_item

  get 'pokrivlja-ogorozhi/mansardni-vikna-daxovi' => 'roof_railing#skylights', as: :skylights
  get 'pokrivlja-ogorozhi/mansardni-vikna-daxovi/:producer' => 'roof_railing#skylight', as: :skylight
  get 'pokrivlja-ogorozhi/mansardni-vikna-daxovi/:producer/:title' => 'roof_railing#skylight_item', as: :skylight_item

  get 'moskitna-sitka' => 'mosquito#index', as: :mosquito_grid
  get 'moskitna-sitka/window' => 'mosquito#window', as: :mosquito_grid_window
  get 'moskitna-sitka/window/:title' => 'mosquito#window_item', as: :one_mosquito_window

  get 'moskitna-sitka/door' => 'mosquito#door', as: :mosquito_grid_doors
  get 'moskitna-sitka/door/:title' => 'mosquito#door_item', as: :one_mosquito_door
  get 'moskitna-sitka/rolling' => 'mosquito#rolling', as: :mosquito_grid_rolling
  get 'moskitna-sitka/rolling/:title' => 'mosquito#rolling_item', as: :one_mosquito_rolling
  get 'moskitna-sitka/sliding' => 'mosquito#sliding', as: :mosquito_grid_sliding
  get 'moskitna-sitka/sliding/:title' => 'mosquito#sliding_item', as: :one_mosquito_sliding

  get 'mataloplastykovi-vikna-i-dveri' => 'window_and_door#index', as: :window_and_door
  post 'wd_order_product' => 'window_and_door#order_product', as: :windowsill_and_door_ordering

  get 'basket' => 'main#basket'
  post 'recently_viewed' => 'main#recently_viewed'

  post 'offers_and_comments' => 'main#offers_and_comments'
  post 'contact_form' => 'main#contact_form'
  post 'call_order' => 'main#call_order'
  post 'order_product' => 'main#order_product'

  get 'finish_step_basket/:id' => 'main#finish_step_basket', as: :basket_items_list

  get 'terms-of-use' => 'main#terms'
  get 'warranty' => 'main#warranty'

  get 'search' => 'main#search'
  get 'sitemap' => 'main#sitemap'

  get 'dev' => 'main#dev'
  get 'dev2' => 'main#dev2'
  get 'dev3' => 'main#dev3'

  post 'get_rr_options/:key' =>'roof_railing#get_rr_options', as: :get_rr_option
  post 'get_metal_tile_options/:key' =>'roof_railing#get_metal_tile_options', as: :get_mt_option
  post 'get_metal_sheet_options/:key' =>'roof_railing#get_metal_sheet_options', as: :get_ms_option
  post "get_product_options/:type/:name" =>'roof_railing#get_product_options', as: :get_product_option
  post "get_fastener_options/:type/:name" =>'roof_railing#get_fastener_options', as: :get_fastener_option

  resources :line_items
  resources :carts

  get "*any", via: :all, to: "errors#not_found"
end

app/views/partials/_call_order.html.slim
#CallOrder.reveal-modal.small data-reveal=""
  .row
    .columns
      strong Замовити дзвінок
      p Введь свій номер телефону і ми самі Вам передзвонимо.

      form.ajax-contact-form.default-animation-form.default-form-with-icons action=call_order_path method="POST"
        .input.animate-input
          .input-ico
            =inline_svg "ic_phone_24px.svg"
          label Контактний телефон
          input name="phone" type="tel" required=""

        .button-wrap.material-component.ripple.right
          button.right type="submit"
            |Надіслати
            = render partial: "partials/loader"

        .material-component.ripple.right
          a.close-reveal-modal aria-label="Close" Закрити

app/views/partials/_contact_form.html.slim
#ContactForm.reveal-modal.small data-reveal=""
  .row
    .columns
      strong Написати нам

      form.ajax-contact-form.default-animation-form.default-form-with-icons action=contact_form_path method="POST"
        .row
          .columns
            .input.animate-input
              .input-ico
                =inline_svg "ic_person_48px.svg"
              label Ваше ім’я
              input name="name" type="text" required=""
        .row
          .columns
            .input.animate-input
              .input-ico
                =inline_svg "ic_phone_24px.svg"
              label Контактний телефон
              input name="phone" type="tel" required=""
        .row
          .columns
            .input.animate-input
              .input-ico
                =inline_svg "ic_mail_24px.svg"
              label Електронна скринька
              input name="email" type="email" required=""
        .row
          .columns
            .input.animate-input.animate-textarea
              .input-ico
                =inline_svg "ic_insert_comment_24px.svg"
              label Текст повідомлення...
              textarea name="message" rows="6"

        .button-wrap.material-component.ripple.right
          button.right type="submit"
            |Надіслати
            = render partial: "partials/loader"

        .material-component.ripple.right
          a.close-reveal-modal aria-label="Close" Закрити

app/views/partials/_gag.html.slim
.one-windowsill
  .ow-image
    a href=one_gag_path(gag.slug)
      - if gag.image.exists?
        .image style="background: url('#{gag.image.url(:thumb)}')no-repeat center center;"
    .show-large-image.lightGallery
      a href=gag.image.url(:large)
        = inline_svg"Valko-icon-search.svg"

  .ow-body
    .ow-body-information
      .small-6.columns
        .title = truncate(gag.title, length: 21, omission: '')
      .small-6.columns
        .price
          = gag.try(:price)
          sup &nbsp;грн.
      .columns
        .brand-title = gag.brand.title
      .clearfix

    .ow-body-order-form
      a href=one_gag_path(gag.slug) Переглянути

app/views/partials/_loader.html.slim
.uil-default-css
  div
  div
  div
  div
  div
  div
  div
  div
  div
  div

app/views/partials/_main_banner.html.slim
.row
  .columns
    .main-banner-wrap
      - if main_banner.main_banner_images && main_banner.main_banner_images.any?
        ul.main-banner
          - main_banner.main_banner_images.sort_by_position.each do |slide|
            li
              .image style="background: url('#{slide.image.url(:large)}')no-repeat center center;"

      .main-banner-description
        .row
          .columns
            .title
              = main_banner.title
        .row
          = raw main_banner.description

app/views/partials/_one_item_card.html.slim
- if item.class.name == "RoofRailItem"
  - item
  - parent = item.rr_description
- if item.class.name == "RrDescription"
  - parent = item
  - item = item.roof_rail_item

/= item.inspect
/hr
/= parent.inspect

- if item
  .one-windowsill
    - if parent.promo_labels && parent.promo_labels.any?
      .ow-status
        - parent.promo_labels.each do |ilb|
          .ows-one
            = image_tag ilb.icon.url(:large)

    .ow-image
      a href=one_decking_path(item.slug)
        /.image style="background: url('#{image}')no-repeat center center;"
        - if item.rr_details && item.rr_details.any?
          .image style="background: url('#{item.rr_details.first.image.url(:thumb)}')no-repeat center center;"

      .show-large-image.lightGallery
        - if item.rr_details.first && item.rr_details.first.image.exists?
          a href=item.rr_details.first.image.url(:large)
            = inline_svg"Valko-icon-search.svg"

    .ow-body
      .ow-body-information
        .small-6.columns
          .title = item.title
        .small-6.columns
          .price data-product-price=(((item.try(&:width).to_f/1000) * 1) * item.rr_details.first.price)
            = (((item.try(&:width).to_f/1000) * 1) * item.rr_details.first.price).round()
            sup &nbsp;грн.
          p
            |від
        .columns
        /.brand-title = gag.brand.title
        .clearfix

      .ow-body-order-form
        /- if title == 'профнастил'
        a href=one_decking_path(item.slug) Переглянути

app/views/partials/_one_item_card2.html.slim
.one-windowsill
  .ow-image
    a
      .image style="background: url('#{image}')no-repeat center center;"
    .show-large-image.lightGallery
      a
        = inline_svg"Valko-icon-search.svg"

  .ow-body
    .ow-body-information
      .small-6.columns
        .title = title
      .small-6.columns
        .price
          /= gag.try(:price)
          sup &nbsp;грн.
      .columns
        /.brand-title = gag.brand.title
      .clearfix

    .ow-body-order-form
      - if title == 'профнастил'
        a href=roof_rail_decking_path Переглянути
      - else
        a Переглянути

app/views/partials/_one_item_mg_card.html.slim
.one-windowsill
  - if item.promo_labels && item.promo_labels.any?
    .ow-status
      - item.promo_labels.each do |ilb|
        .ows-one
          = image_tag ilb.icon.url(:large)
  .ow-image
    - if item.mosquito_grid_type == 'window'
      - link_href = one_mosquito_window_path(item.slug)
    - elsif item.mosquito_grid_type == 'door'
      - link_href = one_mosquito_door_path(item.slug)
    - elsif item.mosquito_grid_type == 'rolling'
      - link_href = one_mosquito_rolling_path(item.slug)
    - elsif item.mosquito_grid_type == 'sliding'
      - link_href = one_mosquito_sliding_path(item.slug)


    a href=link_href
      /.image style="background: url('#{image}')no-repeat center center;"
      - if item.mosquito_item_options && item.mosquito_item_options.any?
        .image style="background: url('#{item.mosquito_item_options.first.image.url(:thumb)}')no-repeat center center;"

    .show-large-image.lightGallery
      - if item.mosquito_item_options.first && item.mosquito_item_options.first.image.exists?
        a href=item.mosquito_item_options.first.image.url(:large)
          = inline_svg"Valko-icon-search.svg"

  .ow-body
    .ow-body-information
      .small-6.columns
        .title = item.title
      .small-6.columns
        .price data-product-price=""
          /= (((item.try(&:width).to_f/1000) * 1) * item.rr_details.first.price).round()
          = item.mosquito_item_options.first.price
          sup &nbsp;грн.
        p
          |від
      .columns
      .clearfix

    .ow-body-order-form
      a href=link_href Переглянути

app/views/partials/_recently_viewed_list.html.slim
.page-block
  .page-block-title
    .row
      .columns
        span
          span.hide-for-small-only
            |Нещодавно&nbsp;
          |пререглянуті:
        #recently-viewed-windowsill-dots.owl-dots

  .carousel-product-list#recently-viewed-windowsill
    - recently_viewed.in_groups_of(4, false).each do |windowsill_sublist|
      .row
        - windowsill_sublist.each do |windowsill|
          .large-3.medium-6.columns class=("end" if recently_viewed.last == windowsill)
            = render "partials/windowsill", windowsill: windowsill

app/views/partials/_windowsill.html.slim
.one-windowsill
  - if windowsill.promo_labels && windowsill.promo_labels.any?
    .ow-status
      - windowsill.promo_labels.each do |item|
        .ows-one
          = image_tag item.icon.url(:large)
  .ow-image
    a href=one_windowsill_path(windowsill.slug)
      - if windowsill.windowsill_photos && windowsill.windowsill_photos.first.image.exists?
        .image style="background: url('#{windowsill.windowsill_photos.first.image.url(:thumb)}')no-repeat center center;"
    .show-large-image.lightGallery
      a href=windowsill.windowsill_photos.first.image.url(:large)
        = inline_svg"Valko-icon-search.svg"
  .ow-body
    .ow-body-information
      .small-6.columns
        .title = truncate(windowsill.title, length: 21, omission: '')
      .small-6.columns
        .price
          = windowsill.prices.first.try(:value)
          sup &nbsp;грн.
        p
          |від
      .columns
        .brand-title
          - if windowsill.wind_type == 'internal'
            = windowsill.brand.title
            - if windowsill.decor.present?
              |,&nbsp;
              = t("enumerize.decor.#{windowsill.decor}").mb_chars.downcase.to_s
            - if windowsill.kapinos.present?
              |,&nbsp
              = t("enumerize.kapinos.#{windowsill.kapinos}").mb_chars.downcase.to_s

          - elsif windowsill.wind_type == 'external'
            = windowsill.brand.title
            - if windowsill.material.present?
              |,&nbsp;
              = t("enumerize.material.#{windowsill.material}").mb_chars.downcase.to_s
            - if windowsill.color_type.present?
              |,&nbsp;
              = t("enumerize.color_type.#{windowsill.color_type}").mb_chars.downcase.to_s
      .clearfix

    .ow-body-order-form
      a href=one_windowsill_path(windowsill.slug) Переглянути