config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'main#index'

  get 'vyrobnictvo-prodazh-montazh-pidvikonnykiv' => 'main#about', as: :about

  get 'informaciia' => 'main#publications', as: :information
  get 'informaciia/:title' => 'main#publication', as: :one_publication

  get 'testimonials' => 'testimonial#list', as: :testimonials

  get 'aktcii' => 'main#promotions', as: :promotions
  get 'aktcii/:title' => 'main#one_promotions', as: :one_promotions

  get 'kontakty' => 'main#contacts', as: :contacts

  get 'dostavka-i-oplata' => 'main#warranty', as: :warranty

  get 'pidvikonnja-vidlyvy' => 'main#windowsill', as: :windowsill
  get 'pidvikonnja-vidlyvy/:title' => 'main#one_windowsill', as: :one_windowsill
  get 'gag/:title' => 'main#gag', as: :one_gag

  get 'pokrivlja-ogorozhi' => 'roof_railing#index', as: :roof_rail
  get 'pokrivlja-ogorozhi/profnastyl-metaloprofil' => 'roof_railing#deck_list', as: :roof_rail_decking
  get 'pokrivlja-ogorozhi/profnastyl-metaloprofil/:title' => 'roof_railing#decking', as: :one_decking

  get 'pokrivlja-ogorozhi/metalocherepitcja' => 'roof_railing#metal_tile_list', as: :metal_tile
  get 'pokrivlja-ogorozhi/metalocherepitcja/:title' => 'roof_railing#metal_tile', as: :metal_tile_item

  get 'pokrivlja-ogorozhi/lystovyj-metal' => 'roof_railing#sheet_metal_list', as: :sheet_metal
  get 'pokrivlja-ogorozhi/lystovyj-metal/:title' => 'roof_railing#sheet_metal', as: :sheet_metal_item

  get 'pokrivlja-ogorozhi/pokrivelni-dobirni-elementy' => 'roof_railing#choicest_items', as: :choicest_items
  get 'pokrivlja-ogorozhi/pokrivelni-dobirni-elementy/the-roof' => 'roof_railing#choicest_roof_items', as: :choicest_roof_items
  get 'pokrivlja-ogorozhi/pokrivelni-dobirni-elementy/the-fence' => 'roof_railing#choicest_fence_items', as: :choicest_fence_items
  get 'pokrivlja-ogorozhi/pokrivelni-dobirni-elementy/:title' => 'roof_railing#choicest_item', as: :choicest_item

  get 'pokrivlja-ogorozhi/kriplennja-germetyka-dlja-pokrivli' => 'roof_railing#mounting_and_sealants', as: :mounting_and_sealants
  get 'pokrivlja-ogorozhi/kriplennja-germetyka-dlja-pokrivli/hermetyky' => 'roof_railing#sealants', as: :sealants
  get 'pokrivlja-ogorozhi/kriplennja-germetyka-dlja-pokrivli/hermetyky/:title' => 'roof_railing#sealant', as: :sealant
  get 'pokrivlja-ogorozhi/kriplennja-germetyka-dlja-pokrivli/kriplennya' => 'roof_railing#mounting', as: :fasteners
  get 'pokrivlja-ogorozhi/kriplennja-germetyka-dlja-pokrivli/kriplennya/:title' => 'roof_railing#fastener', as: :fastener

  get 'pokrivlja-ogorozhi/pokrivelni-plivky' => 'roof_railing#roofing_membrane', as: :roofing_membrane
  get 'pokrivlja-ogorozhi/pokrivelni-plivky/parobaryer' => 'roof_railing#vapour_barrier', as: :vapour_barrier
  get 'pokrivlja-ogorozhi/pokrivelni-plivky/parobaryer/:title' => 'roof_railing#vapour_barrier_item', as: :vapour_barrier_item

  get 'pokrivlja-ogorozhi/pokrivelni-plivky/hidrobaryer' => 'roof_railing#hydro_barrier', as: :hydro_barrier
  get 'pokrivlja-ogorozhi/pokrivelni-plivky/hidrobaryer/:title' => 'roof_railing#hydro_barrier_item', as: :hydro_barrier_item

  get 'pokrivlja-ogorozhi/pokrivelni-plivky/membrana' => 'roof_railing#membrane', as: :membrane
  get 'pokrivlja-ogorozhi/pokrivelni-plivky/membrana/:title' => 'roof_railing#membrane_item', as: :membrane_item

  get 'pokrivlja-ogorozhi/mansardni-vikna-daxovi' => 'roof_railing#skylights', as: :skylights
  get 'pokrivlja-ogorozhi/mansardni-vikna-daxovi/:producer' => 'roof_railing#skylight', as: :skylight
  get 'pokrivlja-ogorozhi/mansardni-vikna-daxovi/:producer/:title' => 'roof_railing#skylight_item', as: :skylight_item

  get 'moskitna-sitka' => 'mosquito#index', as: :mosquito_grid
  get 'moskitna-sitka/window' => 'mosquito#window', as: :mosquito_grid_window
  get 'moskitna-sitka/window/:title' => 'mosquito#window_item', as: :one_mosquito_window

  get 'moskitna-sitka/door' => 'mosquito#door', as: :mosquito_grid_doors
  get 'moskitna-sitka/door/:title' => 'mosquito#door_item', as: :one_mosquito_door
  get 'moskitna-sitka/rolling' => 'mosquito#rolling', as: :mosquito_grid_rolling
  get 'moskitna-sitka/rolling/:title' => 'mosquito#rolling_item', as: :one_mosquito_rolling
  get 'moskitna-sitka/sliding' => 'mosquito#sliding', as: :mosquito_grid_sliding
  get 'moskitna-sitka/sliding/:title' => 'mosquito#sliding_item', as: :one_mosquito_sliding

  get 'mataloplastykovi-vikna-i-dveri' => 'window_and_door#index', as: :window_and_door
  post 'wd_order_product' => 'window_and_door#order_product', as: :windowsill_and_door_ordering

  get 'basket' => 'main#basket'
  post 'recently_viewed' => 'main#recently_viewed'

  post 'offers_and_comments' => 'main#offers_and_comments'
  post 'contact_form' => 'main#contact_form'
  post 'call_order' => 'main#call_order'
  post 'order_product' => 'main#order_product'

  get 'finish_step_basket/:id' => 'main#finish_step_basket', as: :basket_items_list

  get 'terms-of-use' => 'main#terms'
  get 'warranty' => 'main#warranty'

  get 'search' => 'main#search'
  get 'sitemap' => 'main#sitemap'

  get 'dev' => 'main#dev'
  get 'dev2' => 'main#dev2'
  get 'dev3' => 'main#dev3'

  post 'get_rr_options/:key' =>'roof_railing#get_rr_options', as: :get_rr_option
  post 'get_metal_tile_options/:key' =>'roof_railing#get_metal_tile_options', as: :get_mt_option
  post 'get_metal_sheet_options/:key' =>'roof_railing#get_metal_sheet_options', as: :get_ms_option
  post "get_product_options/:type/:name" =>'roof_railing#get_product_options', as: :get_product_option
  post "get_fastener_options/:type/:name" =>'roof_railing#get_fastener_options', as: :get_fastener_option

  resources :line_items
  resources :carts

  get "*any", via: :all, to: "errors#not_found"
end

app/views/partials/basket/_basket_confirmation.html.slim
.row.basket-header
  .medium-5.columns
    .title
      = inline_svg "Valko-icon-basket-step-3.svg"
      |Підтвердження
  .medium-7.columns
    ul.basket-navigation
      li
        .bn-icon 1
        .bn-label Перелік товарів
      li.prev-current
        .bn-icon 2
        .bn-label Доставка
      li.current
        .bn-icon 3
        .bn-label Підтвердження
      .clearfix

.basket-body
  .row
    .columns
      hr
  .row
    .medium-6.columns
      h5 Контактні дані:
      .bc-contacts-info
        .bc-ci-one
          .bc-ci-key Ім’я
          .bc-ci-value.bcv-first-name
            p Тарас
        .bc-ci-one
          .bc-ci-key Прізвище
          .bc-ci-value.bcv-last-name
            p Шевченко
        .bc-ci-one
          .bc-ci-key Телефон
          .bc-ci-value.bcv-phone
            p
        .bc-ci-one
          .bc-ci-key Ел. скринька
          .bc-ci-value.bcv-email
            p Useremail@gmail.com
        .bc-ci-one
          .bc-ci-key Спосіб довозу
          .bc-ci-value.bcv-shipping
            p
        .bc-ci-one
          .bc-ci-key Примітки
          .bc-ci-value.bcv-message
            p

    .medium-6.columns
      #basket-conformation-list
        = render "partials/basket/basket_confirmation_list", cart: @cart

      h5 Спосіб оплати:
      p Можливі різноманітні способи оплати - прохання уточнити у менеджера
.basket-footer
  .row
    .columns
      .material-component.ripple.button-box-shadow.red-button.right.cart-button
        a.finish-step data-href=order_product_path data-action=cart_path(@cart.id)
          |Замовити
          = render partial: "partials/loader"


      .material-component.ripple.button-box-shadow.blue-text.right.cart-button
        a data-step="cart-delivery" До доставки

app/views/partials/basket/_basket_confirmation_list.html.slim
h5 Перелік Товарів:
.bc-basket-list
  .bc-basket-list-body
    - cart.line_items.each do |item|
      - if item.class_name == 'Windowsill'
        / WINDOWSILL
        .row.bc-bl-one
          .small-2.columns
            .image style="background: url('#{item.windowsill.windowsill_photos.first.image.url(:thumb)}')no-repeat center center;"
          .small-7.columns.no-pad-left
            a href=one_windowsill_path(item.windowsill.slug)
              = item.windowsill.title
            p
              span #{item.quantity} шт.
          .small-3.columns
            p
              = (item.total_price(item.long)).round()
              sup грн.
      - if item.class_name == 'Gag'
        / GAG
        .row.bc-bl-one
          .small-2.columns
            .image style="background: url('#{item.gag.image.url(:thumb)}')no-repeat center center;"
          .small-7.columns.no-pad-left
            a href=one_gag_path(item.gag.slug)
              = item.gag.title
            p
              span #{item.quantity} шт.
          .small-3.columns
            p
              = item.total_price.round()
              sup грн.

      - elsif item.class_name == 'Decking'
        / DECKING
        - el = item.roof_rail_item.rr_details.find_by_title(item.color)
        .row.bc-bl-one
          .small-2.columns
            .image style="background: url('#{el.image.url(:thumb)}')no-repeat center center;"
          .small-7.columns.no-pad-left
            a href=one_decking_path(item.roof_rail_item.slug) #{item.roof_rail_item.title} (#{t("enumerize.title.#{item.color}")})
            p
              span #{item.quantity} шт.
          .small-3.columns
            p
              = item.total_price(item.long).round()
              sup грн.

      - elsif item.class_name == 'Mosquito'
        / MOSQUITO
        - el = item.mosquito_item_option
        .row.bc-bl-one
          .small-2.columns
            .image style="background: url('#{el.image.url(:thumb)}')no-repeat center center;"
          .small-7.columns.no-pad-left
            a href=one_mosquito_window_path(item.mosquito_item.slug) #{item.mosquito_item.title} (#{t("enumerize.mosquito_item_option.title.#{el.title}")})
            p
              span #{item.quantity} шт.
          .small-3.columns
            p
              = item.total_price(item.long).round()
              sup грн.

      - elsif item.class_name == 'MetalTile'
        / METAL TILE
        - product = item.metal_tile_detail
        - variant = product.color_options.find_by_title(item.color)
        .row.bc-bl-one
          .small-2.columns
            .image style="background: url('#{variant.image.url(:thumb)}')no-repeat center center;"
          .small-7.columns.no-pad-left
            a href=metal_tile_item_path(product.slug) #{product.title} (#{t("enumerize.title.#{item.color}")})
            p
              span #{item.quantity} шт.
          .small-3.columns
            p
              = item.total_price(item.long).round()
              sup грн.

      - elsif item.class_name == 'MetalSheet'
        / METAL SHEET
        - product = item.metal_sheet_detail
        - variant = product.color_options.find_by_title(item.color)
        .row.bc-bl-one
          .small-2.columns
            .image style="background: url('#{variant.image.url(:thumb)}')no-repeat center center;"
          .small-7.columns.no-pad-left
            a href=sheet_metal_item_path(product.slug) #{product.title} (#{t("enumerize.title.#{item.color}")})
            p
              span #{item.quantity} шт.
          .small-3.columns
            p
              = item.total_price(item.long).round()
              sup грн.


      - elsif item.class_name == 'ChoicestItem'
        / ChoicestItem
        - product = item.choicest_item_detail
        - variant = product.color_options.find_by_title(item.color)
        .row.bc-bl-one
          .small-2.columns
            .image style="background: url('#{variant.image.url(:thumb)}')no-repeat center center;"
          .small-7.columns.no-pad-left
            a href=choicest_item_path(product.slug) #{product.title} (#{t("enumerize.title.#{item.color}")})
            p
              span #{item.quantity} шт.
          .small-3.columns
            p
              = item.total_price(item.long).round()
              sup грн.


      - elsif item.class_name == 'Sealant'
        / Sealant
        - product = item.sealant
        /- variant = product.color_options.find_by_title(item.color)
        .row.bc-bl-one
          .small-2.columns
            .image style="background: url('#{product.image.url(:thumb)}')no-repeat center center;"
          .small-7.columns.no-pad-left
            a href=sealant_path(product.slug) #{product.title}
            p
              span #{item.quantity} шт.
          .small-3.columns
            p
              = item.total_price(item.long).round()
              sup грн.


      - elsif item.class_name == 'Fastener'
        / Fastener
        - product = item.fastener_option
        - variant = product.fastener_color_options.find_by_title(item.color)
        .row.bc-bl-one
          .small-2.columns
            .image style="background: url('#{variant.image.url(:thumb)}')no-repeat center center;"
          .small-7.columns.no-pad-left
            a href=fastener_path(product.slug) #{product.title}
            p
              span #{item.quantity} шт.
          .small-3.columns
            p
              = item.total_price(item.long).round()
              sup грн.


      - elsif item.class_name == 'Membrane'
        / Membrane
        - product = item.membrane
        - link = ""
        - if product.appointment == "vapour_barrier"
          - link = vapour_barrier_item_path(product.slug)
        - elsif product.appointment == "hydro_barrier"
          - link = hydro_barrier_item_path(product.slug)
        - elsif product.appointment == "membrane"
          - link = membrane_item_path(product.slug)

        .row.bc-bl-one
          .small-2.columns
            .image style="background: url('#{product.image.url(:thumb)}')no-repeat center center;"
          .small-7.columns.no-pad-left
            a href=link #{product.title}
            p
              span #{item.quantity} шт.
          .small-3.columns
            p
              = item.total_price(item.long).round()
              sup грн.

      - elsif item.class_name == 'Skylight'
        / Skylight
        - product = item.skylight
        - link = skylight_item_path(product.skylight_model.skylight_producer.slug, product.skylight_model.slug)

        .row.bc-bl-one
          .small-2.columns
            .image style="background: url('#{product.skylight_model.avatar.url(:thumb)}')no-repeat center center;"
          .small-7.columns.no-pad-left
            a href=link #{product.skylight_model.skylight_producer.name} #{product.skylight_model.name} (#{product.size})
            p
              span #{item.quantity} шт.
          .small-3.columns
            p
              = item.total_price(item.long).round()
              sup грн.


  .bc-basket-list-footer
    .bc-bl-total-price
      p
        span Σ:
        b
          = cart.total_price.round()
        sup &nbsp;грн.

app/views/partials/basket/_basket_delivery.html.slim
.row.basket-header
  .medium-5.columns
    .title
      = inline_svg "Valko-icon-basket-step-2.svg"
      |Оформлення замовлення
  .medium-7.columns
    ul.basket-navigation
      li.prev-current
        .bn-icon 1
        .bn-label Перелік товарів
      li.current
        .bn-icon 2
        .bn-label Доставка
      li
        .bn-icon 3
        .bn-label Підтвердження
      .clearfix

.basket-body
  .row
    .columns
      hr
  .row
    .columns
      h5 Контактні дані:
  .columns
    form#basket-contacts-info.ajax-popup-form.default-animation-form.default-form-with-icons data-abide="" action="" method="POST"

      .row
        .medium-6.columns
          .input.animate-input
            .input-ico
              =inline_svg "ic_person_48px.svg"
            label
              |Ваше ім’я
              span ,&nbsp;введено не вірно
            input name="first_name" type="text" required=""

        .medium-6.columns
          .input.animate-input
            .input-ico
              =inline_svg "Valko-icon-username-surname.svg"
            label
              |Прізвище
              span ,&nbsp;введено не вірно
            input name="last_name" type="text" required=""

      .row
        .medium-6.columns
          .input.animate-input
            .input-ico
              =inline_svg "ic_phone_24px.svg"
            label
              |Контактний телефон
              span ,&nbsp;введено не вірно
            input name="phone" type="tel" required="" pattern="(((\+[\d]{2})|[\d]{1,2})?0[0-9]{9})"

        .medium-6.columns
          .input.animate-input
            .input-ico
              =inline_svg "ic_mail_24px.svg"
            label
              |Електронна скринька
              span ,&nbsp;введена не вірно
            input name="email" type="email" required=""

      .row
        .medium-6.columns
          .input.animate-input.animated-select.is-completed
            .input-ico
              =inline_svg "Valko-icon-delivery.svg"
            label Спосіб доставки
            select
              option Самовивіз
              option Нова пошта
              option Міст Експресс
              option Делівері
              option Інше

        .medium-6.columns
          .input.animate-input.animate-textarea
            .input-ico
              =inline_svg "ic_insert_comment_24px.svg"
            label Додаткові примітки
            textarea name="message" rows="1"

    .row
      .medium-6.columns
        p.notes * Місто та номер відділення вкажіть, будь ласка, в полі «Додаткові примітки».
    .clearfix
  .row
    .columns
      h5 Спосіб оплати:
  .row
    .columns
      p Можливі різноманітні способи оплати - прохання уточнити у менеджера

.basket-footer
  .row
    .columns
      .material-component.ripple.button-box-shadow.red-button.right.cart-button.cb-to-confirm
        a data-step="cart-confirmation" data-action=basket_items_list_path(@cart.id) Підтвердити
      .material-component.ripple.button-box-shadow.blue-text.right.cart-button
        a data-step="cart-item-list" До переліку товарів

app/views/partials/basket/_basket_list.html.slim
.row.basket-header
  .medium-5.columns
    .title
      = inline_svg "Valko-icon-korzuna.svg"
      |Перелік товарів
  .medium-7.columns
    ul.basket-navigation
      li.current
        .bn-icon 1
        .bn-label Перелік товарів
      li
        .bn-icon 2
        .bn-label Доставка
      li
        .bn-icon 3
        .bn-label Підтвердження
      .clearfix

.row
  .columns
    .columns
      .basket-list
        - @cart.line_items.each do |item|
          - if item.class_name == 'Windowsill'
            - long = item.long.to_f/1000
            / WINDOWSILL
            -gag_edge_price = 0
            - if item.with_gag && item.windowsill.brand.gag
              - gag_edge_price = item.windowsill.brand.gag.price
            - elsif item.with_edge
              - gag_edge_price = item.windowsill.edge_price
            .basket-list-one data-gag-edge=gag_edge_price data-item-price=(item.price * long)
              .row
                .small-2.medium-1.columns
                  .basket-delete-item-wrap
                    a.delete-item data-href=line_items_path data-line-item-id=item.id
                      = inline_svg "ic_delete_black_24px.svg"
                .hide-for-small-only.medium-2.columns
                  .image style="background: url('#{item.windowsill.windowsill_photos.first.image.url(:thumb)}')no-repeat center center;"
                .small-5.medium-6.columns.no-pad-left-small
                  a href=one_windowsill_path(item.windowsill.slug)
                    .title = item.windowsill.title
                  .brand-title
                    = item.windowsill.brand.title
                    - if item.with_gag.present?
                      |&nbsp;з заглушкою
                    - elsif item.with_edge.present?
                      |&nbsp;з кромкою
                    - elsif item.nonstandard.present?
                      |&nbsp;нестандарт
                  p
                    span Ширина:
                    = item.weight
                    sup &nbsp;мм
                  p
                    span Довжина:
                    = item.long
                    sup &nbsp;мм
                .small-2.medium-1.columns.no-pad-left-small
                  .input.basket-count-product
                    - if item.with_gag.present?
                      input#count-product data-total-price=@cart.total_price min="1" data-old-value=item.quantity type="number" value=item.quantity data-href=line_items_path data-line-item-id=item.id data-type=Windowsill.name data-product-id=item.windowsill.id data-weight=item.weight data-long=item.long data-gag="true"
                    /- elsif item.with_edge.present?

                    - else
                      input#count-product data-total-price=@cart.total_price min="1" data-old-value=item.quantity type="number" value=item.quantity data-href=line_items_path data-line-item-id=item.id data-type=Windowsill.name data-product-id=item.windowsill.id data-weight=item.weight data-long=item.long data-gag="false"

                .small-3.medium-2.columns.no-pad-left-small.no-pad-right-small
                  .one-total-price
                    b
                      = item.total_price(item.long).round()
                    sup &nbsp;грн.

                  .one-price
                    b
                      = item.price
                    sup
                      |&nbsp;грн./м
                      sup 2

          - elsif item.class_name == 'Gag'

            / GAG
            .basket-list-one data-gag-edge='0' data-item-price=item.price
              .row
                .small-2.medium-1.columns
                  .basket-delete-item-wrap
                    a.delete-item data-href=line_items_path data-line-item-id=item.id
                      = inline_svg "ic_delete_black_24px.svg"
                .hide-for-small-only.medium-2.columns
                  .image style="background: url('#{item.gag.image.url(:thumb)}')no-repeat center center;"
                .small-5.medium-6.columns.no-pad-left-small
                  a href=one_gag_path(item.gag.slug)
                    .title = item.gag.title
                  .brand-title = item.gag.brand.title
                .small-2.medium-1.columns.no-pad-left-small
                  .input.basket-count-product
                    input#count-product data-total-price=@cart.total_price min="1" data-old-value=item.quantity type="number" value=item.quantity data-href=line_items_path data-line-item-id=item.id data-type=Windowsill.name data-product-id=item.gag.id

                .small-3.medium-2.columns.no-pad-left-small.no-pad-right-small
                  .one-total-price
                    b
                      = item.total_price
                    sup &nbsp;грн.
                  .one-price
                    b
                      = item.price
                    sup &nbsp;грн./шт.

          - elsif item.class_name == 'Decking'

            /DECKING
            - el = item.roof_rail_item.rr_details.find_by_title(item.color)
            .basket-list-one data-gag-edge='0' data-item-price=item.total_price(item.long).round()
              .row
                .small-2.medium-1.columns
                  .basket-delete-item-wrap
                    a.delete-item data-href=line_items_path data-line-item-id=item.id
                      = inline_svg "ic_delete_black_24px.svg"
                .hide-for-small-only.medium-2.columns
                  .image style="background: url('#{el.image.url(:thumb)}')no-repeat center center;"

                .small-5.medium-6.columns.no-pad-left-small
                  a href=one_decking_path(item.roof_rail_item.slug)
                    .title #{item.roof_rail_item.title} (#{t("enumerize.title.#{item.color}")})
                  .brand-title #{t("enumerize.producer.#{item.roof_rail_item.producer}")}, #{t("enumerize.thickness.#{item.roof_rail_item.thickness}")}, #{t("enumerize.coating.#{item.roof_rail_item.coating}")}, #{t("enumerize.protective_lamina.#{item.roof_rail_item.protective_lamina}")}
                  p
                    span Ширина:
                    = item.roof_rail_item.width
                    sup &nbsp;мм
                  p
                    span Довжина:
                    = item.long
                    sup &nbsp;мм
                .small-2.medium-1.columns.no-pad-left-small
                  .input.basket-count-product
                    input#count-product data-total-price=@cart.total_price min="1" data-old-value=item.quantity type="number" value=item.quantity data-href=line_items_path data-line-item-id=item.id data-type="" data-product-id=""

                .small-3.medium-2.columns.no-pad-left-small.no-pad-right-small
                  .one-total-price
                    b
                      = item.total_price(item.long).round()
                    sup &nbsp;грн.
                  .one-price
                    b
                      = item.price
                    sup
                      |&nbsp;грн./м
                      sup 2

          - elsif item.class_name == 'Mosquito'

            /Mosquito
            - el = item.mosquito_item_option
            .basket-list-one data-gag-edge='0' data-item-price=item.mosquito_item.calculate_one_item(item.long, item.weight)
              .row
                .small-2.medium-1.columns
                  .basket-delete-item-wrap
                    a.delete-item data-href=line_items_path data-line-item-id=item.id
                      = inline_svg "ic_delete_black_24px.svg"
                .hide-for-small-only.medium-2.columns
                  .image style="background: url('#{el.image.url(:thumb)}')no-repeat center center;"

                .small-5.medium-6.columns.no-pad-left-small
                  a href=one_mosquito_window_path(item.mosquito_item.slug)
                    .title #{item.mosquito_item.title} (#{t("enumerize.mosquito_item_option.title.#{el.title}")})
                  .brand-title #{t("enumerize.mosquito_item.#{item.product_options}")}
                  p
                    span Ширина:
                    = item.long
                    sup &nbsp;мм
                  p
                    span Довжина:
                    = item.weight
                    sup &nbsp;мм

                .small-2.medium-1.columns.no-pad-left-small
                  .input.basket-count-product
                    input#count-product data-total-price=@cart.total_price min="1" data-old-value=item.quantity type="number" value=item.quantity data-href=line_items_path data-line-item-id=item.id data-type="" data-product-id=""

                .small-3.medium-2.columns.no-pad-left-small.no-pad-right-small
                  .one-total-price
                    b
                      = item.total_price(item.long).round()
                    sup &nbsp;грн.
                  .one-price
                    b
                      = item.mosquito_item.calculate_one_item(1000, 1000, item.mosquito_item_option.id)
                    sup
                      |&nbsp;грн./м
                      sup 2

          - elsif item.class_name == 'MetalTile'
            /MetalTile
            - product = item.metal_tile_detail
            - variant = product.color_options.find_by_title(item.color)
            = render partial: "partials/basket/templeates/metal_tile", locals: {item: item, product: product, variant: variant}

          - elsif item.class_name == 'MetalSheet'
            /MetalSheet
            - product = item.metal_sheet_detail
            - variant = product.color_options.find_by_title(item.color)
            = render partial: "partials/basket/templeates/metal_sheet", locals: {item: item, product: product, variant: variant}

          - elsif item.class_name == 'ChoicestItem'
            /ChoicestItem
            - product = item.choicest_item_detail
            - variant = product.color_options.find_by_title(item.color)
            = render partial: "partials/basket/templeates/metal_sheet", locals: {item: item, product: product, variant: variant}

          - elsif item.class_name == 'Sealant'
            /Sealant
            - product = item.sealant
            /- variant = product.fastener_color_options.find_by_title(item.color)
            = render partial: "partials/basket/templeates/sealant", locals: {item: item, product: product}

          - elsif item.class_name == 'Fastener'
            /Fastener
            - product = item.fastener_option
            - variant = product.fastener_color_options.find_by_title(item.color)
            = render partial: "partials/basket/templeates/fastener", locals: {item: item, product: product, variant: variant}

          - elsif item.class_name == 'Membrane'
            /Membrane
            - product = item.membrane
            /- variant = product.fastener_color_options.find_by_title(item.color)
            = render partial: "partials/basket/templeates/membrane", locals: {item: item, product: product}

          - elsif item.class_name == 'Skylight'
            /Skylight
            - product = item.skylight
            = render partial: "partials/basket/templeates/skylight", locals: {item: item, product: product}

      .clearfix

.basket-footer
  .row
    .columns
      .basket-total-price
        p
          sub Σ:
          b
            = @cart.total_price.round()
          sup &nbsp;грн.
  .row
    .columns
      .material-component.ripple.button-box-shadow.red-button.right.cart-button
        a.first-step data-step="cart-delivery" Доставка
      .material-component.ripple.button-box-shadow.blue-text.right
        - if request.referer
          a href=URI(request.referer).path Повернутись
        - else
          a href=root_path Повернутись